# Generated by Django 4.0.3 on 2022-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waifus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waifus',
            name='image',
            field=models.CharField(default=1, max_length=50, verbose_name='Karakter Resmi'),
            preserve_default=False,
        ),
    ]
